### ISSUE TITLE
Transform a yaml node file in a suitable Zabbix LLD format

### ISSUE THREAD

**Issue by jschaeff** [EIDA/oculus-monitoring-backend#13]
Write a program that transforms the following dictionary in Zabbix LLD json format.

Normally there should never be any table in those descriptions.

Example:

```yaml
---
node: LMU
endpoint: erde.geophysik.uni-muenchen.de
routingFile: eidaws/routing/routing.xml
onlineCheck:
    net: BW
    sta: FFB1
    loc: ""
    cha: HHZ
    start: 2017-05-20T00:00:00
    end: 2017-05-20T00:00:05
perfCheck:
    dataselect:
        9streams:
            net: BW
            sta: "FFB?"
            loc: ""
            cha: HHZ
            start: 2017-05-20T00:00:00
            end: 2017-05-20T00:01:00
        54streams:
            net: BW
            sta: "FFB?"
            loc: ""
            cha: HHZ
            start: 2017-05-20T00:00:00
            end: 2017-05-20T00:01:00
        320streams:        
            net: BW
            sta: "FFB?"
            loc: ""
            cha: HHZ
            start: 2017-05-20T00:00:00
            end: 2017-05-20T00:01:00
        1stream20days:
            net: BW
            sta: "FFB1"
            loc: ""
            cha: HHZ
            start: 2017-05-01T00:00:00
            end: 2017-05-21T00:00:00
    wfcatalog:
        9streams:
            net: BW
            sta: "FFB?"
            loc: ""
            cha: HHZ
            start: 2017-05-20T00:00:00
            end: 2017-05-20T00:01:00
        54streams:
            net: BW
            sta: "FFB?"
            loc: ""
            cha: HHZ
            start: 2017-05-20T00:00:00
            end: 2017-05-20T00:01:00
        320streams:        
            net: BW
            sta: "FFB?"
            loc: ""
            cha: HHZ
            start: 2017-05-20T00:00:00
            end: 2017-05-20T00:01:00
        1stream20days:
            net: BW
            sta: "FFB1"
            loc: ""
            cha: HHZ
            start: 2017-05-01T00:00:00
            end: 2017-05-21T00:00:00
    availability:
        9streams:
            net: BW
            sta: "FFB?"
            loc: ""
            cha: HHZ
            start: 2017-05-20T00:00:00
            end: 2017-05-21T00:00:00
        54streams:
            net: BW
            sta: "FFB?"
            loc: ""
            cha: HHZ
            start: 2017-05-20T00:00:00
            end: 2017-05-21T00:00:00
        320streams:        
            net: BW
            sta: "FFB?"
            loc: ""
            cha: HHZ
            start: 2017-05-20T00:00:00
            end: 2017-05-21T00:00:00
        1stream20days:
            net: BW
            sta: "FFB1"
            loc: ""
            cha: HHZ
            start: 2017-05-01T00:00:00
            end: 2017-05-21T00:00:00
    station:
        9streams:
            net: BW
            sta: "FFB?"
            loc: ""
            cha: HHZ
            start: 2017-05-20T00:00:00
            end: 2017-05-20T00:01:00
        54streams:
            net: BW
            sta: "FFB?"
            loc: ""
            cha: HHZ
            start: 2017-05-20T00:00:00
            end: 2017-05-20T00:01:00
        320streams:        
            net: BW
            sta: "FFB?"
            loc: ""
            cha: "HH?"
            start: 2017-05-20T00:00:00
            end: 2017-05-20T00:01:00
```

The transformation rule should be:

- prefix the variable with `{#EIDA_`
- flatten the dictionarry
- uppercase all the keys
- separate levels by `_`
